### ISSUE TITLE
Tried using it and got a SSL error

### ISSUE THREAD

**Issue by Abdisalan** [rusty122/tufts-meals#1]
Traceback (most recent call last):
  File "tufts-meals.py", line 32, in <module>
    res  = requests.post(URL + "/login.php", data, allow_redirects=False)
  File "/Users/abdisalan/tufts-meals/env/lib/python2.7/site-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, *_kwargs)
  File "/Users/abdisalan/tufts-meals/env/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, *_kwargs)
  File "/Users/abdisalan/tufts-meals/env/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, *_send_kwargs)
  File "/Users/abdisalan/tufts-meals/env/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, *_kwargs)
  File "/Users/abdisalan/tufts-meals/env/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)

**Comment by rusty122** [comment]
Hmmm, this is a puzzler. What version of requests do you have?

**Comment by Abdisalan** [comment]
requests==2.11.1
